# Common proper nouns (first names, countries, cities, brands, food, pop culture)
# that are widely known among English speakers but absent from standard dictionaries.
# All lowercase — unioned into the game dictionary at load time.

PROPER_NOUNS: frozenset = frozenset({

    # ── Male first names ──────────────────────────────────────────────────────
    "aaron", "adam", "alan", "albert", "alex", "alexis", "alfred", "allen",
    "andrew", "andy", "anthony", "antonio", "arthur", "austin",
    "benjamin", "billy", "bobby", "brad", "brandon", "brian", "bruce", "bryan",
    "carlos", "carl", "charles", "charlie", "chris", "christopher", "clarence",
    "craig", "curtis",
    "dale", "daniel", "danny", "david", "dennis", "derek", "donald", "douglas",
    "dylan",
    "earl", "edward", "eric", "ernest", "eugene",
    "frank", "fred", "gary", "george", "gerald", "glen", "gregory",
    "harold", "harry", "henry", "howard",
    "jack", "jacob", "james", "jason", "jeff", "jeffrey", "jeremy", "jesse",
    "jimmy", "joe", "joel", "john", "johnny", "jonathan", "jose", "joseph",
    "joshua", "juan", "justin",
    "keith", "kenneth", "kevin",
    "larry", "lawrence", "leonard", "lewis", "louis", "luis", "luke",
    "manuel", "mark", "martin", "marvin", "matthew", "michael", "mike",
    "nathan", "neil", "nicholas", "noah", "norman",
    "oliver", "patrick", "paul", "peter", "phillip",
    "ralph", "randy", "raymond", "richard", "robert", "rodney", "roger",
    "ronald", "ross", "roy", "russell", "ryan",
    "samuel", "scott", "sean", "shawn", "stanley", "stephen", "steve", "steven",
    "terry", "thomas", "timothy", "todd", "tom", "tony", "travis", "tyler",
    "victor", "vincent",
    "walter", "wayne", "william", "willie",
    "zachary", "zach",
    # extras — popular/modern
    "liam", "elijah", "mason", "logan", "lucas", "aiden", "ethan",
    "caleb", "owen", "sebastian", "gabriel", "nolan",
    "brendan", "colton", "wyatt", "hunter", "evan", "caden", "jaxon",
    "leo", "max", "finn", "kai", "eli", "ian",
    # international / diverse
    "darius", "darian", "emmett", "emilio",
    "fabian", "felipe", "fernando",
    "giovanni", "gideon", "griffin",
    "hector", "hudson", "hugo",
    "ibrahim", "isaiah", "ivan",
    "jasper", "javier",
    "kieran",
    "leandro", "lorenzo",
    "marcelo", "mateo", "maverick",
    "nico", "nikolai",
    "orion", "oscar",
    "pierce", "quentin",
    "rafael", "raphael", "remington",
    "santiago", "santos",
    "thiago", "tobias", "tristan",
    "ulysses", "uriel",
    "valentino", "weston",
    "xander", "xavier",
    "yahir", "yusuf",
    "zion", "zander",

    # ── Female first names ────────────────────────────────────────────────────
    "abigail", "alexis", "alice", "amanda", "amber", "amy", "andrea", "angela",
    "ann", "anna", "ashley",
    "barbara", "beverly", "brenda", "brittany", "britney", "brooke",
    "carol", "carolyn", "catherine", "cheryl", "christina", "christine",
    "cynthia",
    "danielle", "deborah", "debra", "denise", "diana", "diane", "donna",
    "dorothy",
    "elizabeth", "emily", "emma", "evelyn",
    "frances",
    "gloria", "grace",
    "hannah", "heather", "helen",
    "jacqueline", "janet", "janice", "jean", "jennifer", "jessica", "joan",
    "joyce", "judith", "julia", "julie",
    "karen", "katherine", "kathleen", "kathryn", "kayla", "kelly", "kimberly",
    "laura", "lauren", "linda", "lisa", "lori",
    "madison", "margaret", "maria", "marie", "marilyn", "martha", "mary",
    "megan", "melissa", "michelle",
    "nancy", "natalie", "nicole",
    "olivia",
    "pamela", "patricia",
    "rachel", "rebecca", "rose",
    "samantha", "sandra", "sara", "sarah", "sharon", "shirley", "stephanie",
    "susan",
    "teresa", "theresa", "tiffany",
    "victoria",
    # extras — popular/modern
    "ava", "sophia", "isabella", "mia", "luna", "chloe", "ella",
    "nora", "lily", "ellie", "zoe", "leah", "penelope", "riley", "layla",
    "aria", "maya", "aurora", "violet", "hazel", "stella", "willow", "scarlett",
    "camila", "addison", "claire", "skylar", "alexa", "brianna", "savannah",
    "audrey", "brooklyn", "avery", "eleanor", "taylor", "paige",
    "faith", "eve", "ruby", "georgia",
    # international / diverse
    "adriana", "adrienne", "alicia", "alyssa", "anita", "anya",
    "berenice", "bianca", "blanche",
    "cassandra", "cassidy", "charlotte", "chelsea", "clarissa", "claudia",
    "courtney", "crystal",
    "darlene", "dawn", "destiny",
    "eileen", "elaine", "elisa", "esperanza",
    "felicia", "fiona",
    "gabrielle", "gemma", "gwendolyn",
    "hailey", "heidi", "holly",
    "ingrid", "iris", "ivy",
    "jade", "jamie", "jasmine", "juliette", "juniper",
    "kylie", "lacey", "leila", "lena", "lorraine", "lucia",
    "mackenzie", "mariana", "mikaela", "miranda", "molly", "monica",
    "nadine", "naomi",
    "phoebe", "priya",
    "raquel", "renee", "roxanne",
    "selena", "serena", "sienna", "sierra",
    "tanya", "tonya", "sonya", "tara", "tatiana",
    "uma", "ursula",
    "valentina", "vera", "vivian", "vivienne",
    "wanda", "wendy", "whitney",
    "xiomara", "ximena",
    "yasmin", "yasmine",
    "yolanda", "yvonne", "yvette",
    "zara", "zelda",

    # ── Countries ─────────────────────────────────────────────────────────────
    "afghanistan", "albania", "algeria", "andorra", "angola", "argentina",
    "armenia", "australia", "austria", "azerbaijan",
    "bahamas", "bahrain", "bangladesh", "belarus", "belgium", "belize",
    "benin", "bhutan", "bolivia", "botswana", "brazil", "brunei", "bulgaria",
    "burundi",
    "cambodia", "cameroon", "canada", "chad", "chile", "china", "colombia",
    "comoros", "congo", "croatia", "cuba", "cyprus",
    "denmark", "djibouti", "dominica",
    "ecuador", "egypt", "eritrea", "estonia", "ethiopia",
    "fiji", "finland", "france",
    "gabon", "gambia", "georgia", "germany", "ghana", "greece", "grenada",
    "guatemala", "guinea", "guyana",
    "haiti", "honduras", "hungary",
    "iceland", "india", "indonesia", "iran", "iraq", "ireland", "israel", "italy",
    "jamaica", "japan", "jordan",
    "kazakhstan", "kenya", "kiribati", "kosovo", "kuwait", "kyrgyzstan",
    "laos", "latvia", "lebanon", "lesotho", "liberia", "libya",
    "liechtenstein", "lithuania", "luxembourg",
    "madagascar", "malawi", "malaysia", "maldives", "mali", "malta",
    "mauritania", "mauritius", "mexico", "moldova", "monaco", "mongolia",
    "montenegro", "morocco", "mozambique", "myanmar",
    "namibia", "nauru", "nepal", "netherlands", "nicaragua", "niger", "nigeria",
    "norway",
    "oman",
    "pakistan", "palau", "panama", "paraguay", "peru", "philippines", "poland",
    "portugal",
    "qatar",
    "romania", "russia", "rwanda",
    "samoa", "senegal", "serbia", "seychelles", "singapore", "slovakia",
    "slovenia", "somalia", "spain", "sudan", "suriname", "sweden", "switzerland",
    "syria",
    "taiwan", "tajikistan", "tanzania", "thailand", "togo", "tonga",
    "trinidad", "tunisia", "turkey", "turkmenistan", "tuvalu",
    "uganda", "ukraine", "uruguay", "uzbekistan",
    "vanuatu", "venezuela", "vietnam",
    "yemen",
    "zambia", "zimbabwe",

    # ── Major cities ──────────────────────────────────────────────────────────
    "london", "paris", "berlin", "tokyo", "beijing", "moscow", "dubai",
    "istanbul", "rome", "madrid", "barcelona", "amsterdam", "vienna", "prague",
    "budapest", "warsaw", "stockholm", "oslo", "helsinki", "copenhagen",
    "brussels", "lisbon", "athens",
    "cairo", "lagos", "nairobi", "johannesburg", "casablanca", "accra",
    "tunis", "khartoum", "dakar", "kampala", "kinshasa", "maputo", "lusaka",
    "harare", "luanda", "abuja",
    "manila", "bangkok", "jakarta", "singapore", "hanoi", "colombo", "dhaka",
    "karachi", "mumbai", "delhi", "lahore", "kabul", "tehran", "baghdad",
    "riyadh", "ankara", "beirut", "amman", "jerusalem",
    "sydney", "melbourne", "auckland",
    "toronto", "montreal", "vancouver",
    "chicago", "houston", "phoenix", "philadelphia", "detroit", "dallas",
    "seattle", "miami", "atlanta", "boston", "denver", "minneapolis",
    "portland", "sacramento", "tampa", "pittsburgh", "cleveland", "nashville",
    "memphis", "louisville", "buffalo", "raleigh", "charlotte", "austin",
    "tucson", "honolulu", "anchorage",
    "brooklyn", "bronx", "manhattan", "queens",

    # ── US states ─────────────────────────────────────────────────────────────
    "alabama", "alaska", "arizona", "arkansas", "california", "colorado",
    "connecticut", "delaware", "florida", "georgia", "hawaii", "idaho",
    "illinois", "indiana", "iowa", "kansas", "kentucky", "louisiana", "maine",
    "maryland", "massachusetts", "michigan", "minnesota", "mississippi",
    "missouri", "montana", "nebraska", "nevada", "hampshire", "jersey",
    "mexico", "york", "carolina", "dakota", "ohio", "oklahoma", "oregon",
    "pennsylvania", "rhode", "tennessee", "texas", "utah", "vermont",
    "virginia", "washington", "wisconsin", "wyoming",

    # ── Food & drink (widely known, not in Webster's) ─────────────────────────
    "hummus", "quinoa", "sriracha", "matcha", "kombucha", "tiramisu",
    "pho", "ramen", "sashimi", "edamame", "tempeh", "miso", "kimchi",
    "shawarma", "falafel", "gyro", "tzatziki", "baklava",
    "guacamole", "burrito", "quesadilla", "enchilada", "tamale", "churro",
    "empanada", "paella", "tapas", "bruschetta", "focaccia", "ciabatta",
    "naan", "pita", "injera", "bibimbap", "bulgogi", "teriyaki", "soba",
    "udon", "dumplings", "wonton", "congee",
    "espresso", "cappuccino", "americano", "macchiato", "frappuccino",
    "latte", "boba", "chai",
    "tequila", "mezcal", "sake", "prosecco", "mojito", "margarita",
    "sriracha", "tahini", "harissa", "chimichurri",

    # ── Tech / brands that became common words ────────────────────────────────
    "google", "googled", "googling", "googles",
    "photoshop", "photoshopped", "photoshopping",
    "snapchat", "instagram", "facebook", "youtube", "netflix",
    "spotify", "amazon", "uber", "lyft", "venmo", "tinder",
    "reddit", "discord", "twitch", "tiktok", "whatsapp", "skype",
    "linkedin", "pinterest", "etsy", "paypal",
    "iphone", "android", "bluetooth", "smartphone",
    "app", "apps", "wifi",
    "bitcoin", "ethereum", "blockchain", "crypto", "cryptocurrency", "nft",

    # ── Pop culture / fandom ──────────────────────────────────────────────────
    "anime", "manga", "otaku", "cosplay", "kawaii",
    "pokemon", "pikachu", "zelda", "minecraft", "fortnite", "roblox",
    "avatar", "hogwarts", "jedi", "sith", "skywalker", "gandalf", "hobbit",
    "targaryen", "lannister", "stark", "daenerys", "khaleesi",
    "spiderman", "batman", "superman", "avengers", "thor", "hulk", "ironman",
    "netflix", "disney", "pixar", "marvel", "dc",
    "esports", "vlog", "vlogger", "youtuber", "influencer", "streamer",
    "twitch", "podcast",

    # ── Other widely known words absent from Webster's ────────────────────────
    "jacuzzi", "frisbee", "popsicle", "velcro", "kleenex", "xerox",
    "styrofoam", "tupperware",
    "covid", "pandemic", "vaccine", "omicron",
    "emoji", "selfie", "hashtag", "meme", "gif", "viral", "trending",
    "cryptocurrency", "metaverse", "deepfake", "chatbot",
    "uber", "airbnb", "doordash", "grubhub",
    "taser", "botox", "adderall",
    "brexit", "trumpism", "maga",

    # ── Demonyms / nationality words (often missing from dictionaries) ────────
    "italian", "italians",
    "american", "americans",
    "canadian", "canadians",
    "mexican", "mexicans",
    "brazilian", "brazilians",
    "australian", "australians",
    "german", "germans",
    "russian", "russians",
    "korean", "koreans",
    "japanese",
    "chinese",
    "indian", "indians",
    "african", "africans",
    "european", "europeans",
    "asian", "asians",
    "latino", "latinos", "latina", "latinas",
    "hispanic", "hispanics",
    "scandinavian", "scandinavians",
    "norwegian", "norwegians",
    "swedish", "swedes",
    "danish", "danes",
    "dutch",
    "greek", "greeks",
    "turkish",
    "polish",
    "ukrainian", "ukrainians",
    "iranian", "iranians",
    "pakistani", "pakistanis",
    "nigerian", "nigerians",
    "ethiopian", "ethiopians",
    "colombian", "colombians",
    "argentinian", "argentinians",
    "peruvian", "peruvians",
    "venezuelan", "venezuelans",
    "cuban", "cubans",
    "jamaican", "jamaicans",
    "haitian", "haitians",
    "dominican", "dominicans",
    "chilean", "chileans",
    "bolivian", "bolivians",
    "ecuadorian", "ecuadorians",
    "guatemalan", "guatemalans",
    "honduran", "hondurans",
    "salvadoran", "salvadorans",
    "panamanian", "panamanians",
    "costa rican",
    "costarican", "costaricans",
    "egyptian", "egyptians",
    "moroccan", "moroccans",
    "algerian", "algerians",
    "tunisian", "tunisians",
    "libyan", "libyans",
    "sudanese",
    "kenyan", "kenyans",
    "ghanaian", "ghanaians",
    "senegalese",
    "congolese",
    "cameroonian", "cameroonians",
    "ugandan", "ugandans",
    "tanzanian", "tanzanians",
    "vietnamese",
    "thai",
    "indonesian", "indonesians",
    "malaysian", "malaysians",
    "filipino", "filipinos", "filipina", "filipinas",
    "cambodian", "cambodians",
    "burmese",
    "bangladeshi", "bangladeshis",
    "nepalese",
    "sri lankan",
    "afghan", "afghans",
    "iraqi", "iraqis",
    "syrian", "syrians",
    "lebanese",
    "jordanian", "jordanians",
    "saudi", "saudis",
    "emirati", "emiratis",
    "kuwaiti", "kuwaitis",
    "qatari", "qataris",
    "israelis",
    "palestinian", "palestinians",
    "kazakh",
    "uzbek",
    "tajik",
    "georgian",
    "armenian", "armenians",
    "azerbaijani", "azerbaijanis",
    "moldovan", "moldovans",
    "belarusian", "belarusians",
    "latvian", "latvians",
    "lithuanian", "lithuanians",
    "estonian", "estonians",
    "hungarian", "hungarians",
    "romanian", "romanians",
    "bulgarian", "bulgarians",
    "serbian", "serbians",
    "croatian", "croatians",
    "slovenian", "slovenians",
    "slovak", "slovaks",
    "czech", "czechs",
    "albanian", "albanians",
    "macedonian", "macedonians",
    "bosnian", "bosnians",
    "montenegrin", "montenegrins",
    "swiss",
    "austrian", "austrians",
    "belgian", "belgians",
    "portuguese",
    "spaniard", "spaniards",
    "brit", "brits",
    "irishman", "irishmen",
    "scotsman", "scotsmen",
    "welshman", "welshmen",
    "finn", "finns",
    "icelander", "icelanders",
    "kiwi", "kiwis",
    "singaporean", "singaporeans",
    "taiwanese",
    "hongkonger", "hongkongers",
    "tibetan", "tibetans",

})
