# Supplemental informal, online, and gaming words not reliably found in
# standard dictionaries.  Unioned with the english-words base set at load time.
# All entries must be purely alphabetic (no apostrophes, hyphens, spaces) —
# the game's is_valid_word() rejects anything that fails .isalpha().

SLANG_WORDS: frozenset = frozenset({

    # ── Informal spoken / written ──────────────────────────────────────────
    "gonna", "wanna", "gotta", "kinda", "sorta", "lotta", "outta",
    "dunno", "gimme", "lemme", "tho", "thru", "nite",
    "yep", "yup", "nope", "yall", "yer", "cuz", "cos", "coz",
    "imma", "tryna", "finna", "hafta",
    "welp", "mhm", "nah", "yeh", "ugh", "hmm",
    "oopsie", "oopsies", "whoops",

    # ── Internet abbreviations (alpha-only, ≥3 chars) ──────────────────────
    "yolo", "fomo", "jomo",
    "smh", "tbh", "ngl", "imo", "imho", "irl",
    "brb", "afk", "bff", "bffs",
    "omg", "lmao", "rofl", "rotfl", "lmfao", "omfg",
    "atm", "btw", "fyi", "aka", "diy", "eta",
    "idk", "nvm", "tbf", "istg", "ootd", "tfw", "smdh",
    "asap", "ggez",

    # ── Exclamations / reactions ───────────────────────────────────────────
    "sheesh", "yikes", "oof", "bruh", "bro", "sis",
    "fam", "bestie", "besties",
    "pog", "poggers", "pogchamp", "kek",
    "dude", "dudes", "babe", "babes",
    "sus", "sussy",
    "periodt",

    # ── Gen Z / Gen Alpha slang ────────────────────────────────────────────
    "skibidi",
    "sigma", "sigmas",
    "rizz", "rizzed", "rizzing", "rizzler", "rizzlers",
    "gyat", "gyats",
    "bussin", "bussing",
    "nocap",
    "snatched",
    "lewk", "lewks",
    "drip", "dripped", "dripping", "drips", "drippy",
    "steez", "steezy",
    "based",
    "cap", "caps", "capping", "capped",
    "ratio", "ratioed", "ratioing", "ratios",
    "simp", "simps", "simping", "simped",
    "chad", "chads", "gigachad", "gigachads",
    "incel", "incels",
    "normie", "normies",
    "coomer", "coomers",
    "doomer", "doomers",
    "zoomer", "zoomers",
    "boomer", "boomers",
    "karen", "karens",
    "npc", "npcs",
    "copium", "hopium",
    "seethe", "seething", "seethes", "seethed",
    "cope", "coped", "coping", "copes",
    "mald", "malded", "malding", "malds",
    "mogging", "mog", "mogs", "mogged", "mogger",
    "yapper", "yap", "yaps", "yapped", "yapping", "yappers",
    "glazing", "glaze", "glazed", "glazes", "glazer", "glazers",
    "brainrot",
    "doomscrolling", "doomscroll", "doomscrolls", "doomscrolled",
    "situationship", "situationships",
    "ghosting", "ghosted",
    "breadcrumbing", "breadcrumb", "breadcrumbs", "breadcrumbed",
    "gaslighting", "gaslit",
    "ick", "icks",
    "glowup", "glowups",
    "looksmaxx", "looksmaxxing",
    "maxxing", "maxx",
    "grindset", "grindsets",
    "alpha", "alphas", "beta", "betas", "omega", "omegas",
    "stacy",
    "redpilled", "redpill", "redpills", "redpilling",
    "bluepilled", "bluepill",
    "blackpilled", "blackpill",
    "triggered", "trigger", "triggers",
    "snowflake", "snowflakes",
    "woke", "wokeness",
    "lit", "litty",
    "dank", "danks",
    "goated",
    "slay", "slayed", "slaying", "slays",
    "slapper", "slappers",
    "banger", "bangers",
    "slaps",
    "bop", "bops",
    "lowkey", "highkey",
    "hype", "hyped",
    "clout", "clouts", "clouted",
    "salty", "saltier", "saltiest",
    "toxic",
    "tilted", "tilt", "tilts", "tilting",
    "vibe", "vibes", "vibing", "vibed",
    "mood",
    "tea",
    "shade",
    "receipts",
    "flex", "flexed", "flexing", "flexes", "flexer", "flexers",
    "swag", "swaggy",
    "bling", "blinged",
    "finesse", "finessed", "finessing", "finesses",
    "hustle", "hustles", "hustled", "hustling", "hustler", "hustlers",
    "grind", "grinding", "grinds",
    "guap", "guaps",
    "standom", "standoms",
    "fandom", "fandoms",
    "fangirl", "fangirled", "fangirling", "fangirls",
    "fanboy", "fanboyed", "fanboying", "fanboys",
    "lowrider", "lowriders",

    # ── Relationship / dating ──────────────────────────────────────────────
    "rizzing",
    "lovebombing", "lovebombed",
    "benching", "benched",
    "hookup", "hookups",
    "rebound", "rebounds",
    "thirsty",

    # ── Social media / influencer ──────────────────────────────────────────
    "haul", "hauls", "hauling",
    "unboxing", "unboxed", "unbox",
    "callout", "callouts",
    "catfish", "catfished", "catfishing", "catfishes",
    "doxxed", "doxxing",
    "swatted", "swatting",
    "parasocial", "parasocials",
    "finsta", "finstas",
    "viral",
    "trending",
    "influencer", "influencers",
    "collab", "collabs", "collabing",
    "unfriend", "unfriended", "unfriending",
    "unfollow", "unfollowed", "unfollowing",
    "tweet", "tweets", "tweeted", "tweeting",
    "retweet", "retweets", "retweeted",
    "texting", "texted",
    "wifi", "hotspot",
    "hashtag", "hashtags",
    "podcast", "podcasts", "podcasting",
    "blogging", "blogger", "bloggers",
    "streamer", "streamers", "streaming", "streamed",
    "vlog", "vlogs", "vlogged", "vlogging", "vlogger", "vloggers",
    "selfie", "selfies",
    "emoji", "emojis",
    "meme", "memes", "memed", "meming",
    "troll", "trolled", "trolling", "trolls",
    "spam", "spammed", "spamming",

    # ── Gaming ────────────────────────────────────────────────────────────
    "noob", "noobs", "nub", "nubs",
    "pwn", "pwned", "pwning",
    "gank", "ganked", "ganking", "ganks",
    "nerf", "nerfed", "nerfing", "nerfs",
    "buff", "buffed", "buffing", "buffs",
    "loot", "looted", "looting", "loots",
    "glitch", "glitched", "glitching", "glitches",
    "modded", "modding", "modder", "modders",
    "devs", "dev",
    "lagged", "lagging", "lags", "lag", "laggy",
    "gamer", "gamers", "gaming",
    "tryhard", "tryhards", "tryharding",
    "sweaty",
    "clutch", "clutched", "clutching",
    "noscope", "noscoped", "noscoping",
    "respawn", "respawns", "respawned", "respawning",
    "griefer", "griefers", "griefed", "griefing",
    "camper", "campers",
    "sniped", "sniping", "sniper", "snipers",
    "flanked", "flanking", "flanker", "flankers",
    "eco", "ecos",
    "crit", "crits", "critting",
    "healer", "healers",
    "kited", "kiting",
    "aggro",
    "minmax", "minmaxed", "minmaxing",
    "smurf", "smurfed", "smurfing", "smurfs",
    "boosted", "booster", "boosters",
    "duo", "duos", "duoing",
    "squad", "squads", "squadding",
    "premade", "premades",
    "ult", "ulted", "ulting", "ults",
    "proc", "procs", "procced", "proccing",
    "monkas", "sadge",

    # ── Bartending / mixology ─────────────────────────────────────────────
    "mix", "mixes", "mixed", "mixing", "mixer", "mixers",
    "mixology", "mixologist", "mixologists",
    "mocktail", "mocktails",
    "bartender", "bartenders", "bartending",

    # ── Hip hop / urban ────────────────────────────────────────────────────
    "hiphop",
    "trapping", "trapper", "trappers",
    "freestyle", "freestyles", "freestyling", "freestyled", "freestyler",
    "cypher", "cyphers",
    "sesh", "seshes",
    "dap", "daps", "dapping",
    "fye",

    # ── Party / nightlife ──────────────────────────────────────────────────
    "pregame", "pregamed", "pregaming", "pregames",
    "afterparty", "afterparties",
    "sloshed",
    "turnt",
    "litty",
    "rager", "ragers",
    "kickback", "kickbacks",
    "hangout", "hangouts",
    "chillin", "chilling",

    # ── Misc modern slang ─────────────────────────────────────────────────
    "yeet", "yeeted", "yeeting", "yeets",
    "stan", "stans", "stanning", "stanned",
    "cringe", "cringey", "cringed",
    "owned", "owns",
    "bitcoin", "ethereum", "blockchain", "crypto", "cryptocurrency", "nft",
    "metaverse", "deepfake", "chatbot",
    "goat",
    "clutching",
})
