# People data for retardguesser game
# 650 entries — generated in batches; do not edit manually
# Bios deliberately omit the subject's first and last name.

PEOPLE = {
    "Jesus Christ": {
        "name": "Jesus Christ",
        "profession": "religious figure",
        "bio": "Born in Bethlehem and raised in Nazareth, widely regarded as the central figure of Christianity and the Son of God by believers. His teachings on love, forgiveness, and salvation are recorded in the four Gospels of the New Testament. Crucified under Roman governor Pontius Pilate around 30–33 AD, with billions believing he rose from the dead three days later.",
        "known_for": "Sermon on the Mount, crucifixion and resurrection, founding of Christianity, the Lord's Prayer",
    },
    "Muhammad": {
        "name": "Muhammad",
        "profession": "Islamic prophet",
        "bio": "Born in Mecca around 570 AD, he is regarded as the founder of Islam and the last prophet of God in Islamic tradition. He received divine revelations later compiled into the Quran, the holy book of Islam. He united the Arabian Peninsula under the new faith before his death in 632 AD.",
        "known_for": "founding of Islam, the Quran, Night Journey (Isra and Mi'raj), Hijra to Medina",
    },
    "William Shakespeare": {
        "name": "William Shakespeare",
        "profession": "playwright",
        "bio": "An English playwright and poet born in Stratford-upon-Avon in 1564, widely considered the greatest writer in the English language. He produced 37 plays and 154 sonnets that remain central to the literary canon. His works have been translated into every major language and are performed more often than those of any other playwright in history.",
        "known_for": "Hamlet, Romeo and Juliet, Macbeth, A Midsummer Night's Dream",
    },
    "Albert Einstein": {
        "name": "Albert Einstein",
        "profession": "physicist",
        "bio": "A German-born physicist who developed the theory of relativity, one of the two pillars of modern physics. His mass-energy equivalence formula E=mc² has become the world's most famous equation. He received the Nobel Prize in Physics in 1921 for his discovery of the law of the photoelectric effect.",
        "known_for": "theory of relativity, E=mc², Nobel Prize in Physics, general relativity",
    },
    "Abraham Lincoln": {
        "name": "Abraham Lincoln",
        "profession": "U.S. president",
        "bio": "The 16th President of the United States, he led the nation through the Civil War and worked to preserve the Union. He issued the Emancipation Proclamation in 1863, declaring enslaved people in Confederate states to be free. He was assassinated by John Wilkes Booth at Ford's Theatre in Washington, D.C. in 1865.",
        "known_for": "Emancipation Proclamation, Civil War leadership, Gettysburg Address, assassination at Ford's Theatre",
    },
    "George Washington": {
        "name": "George Washington",
        "profession": "founding father",
        "bio": "The commander-in-chief of the Continental Army during the American Revolutionary War, he led the colonies to victory against Britain. He served as the first President of the United States from 1789 to 1797 and is often called the Father of His Country. He set a key precedent by voluntarily stepping down from power after two terms.",
        "known_for": "American Revolutionary War, first U.S. president, crossing the Delaware, Mount Vernon",
    },
    "Adolf Hitler": {
        "name": "Adolf Hitler",
        "profession": "dictator",
        "bio": "An Austrian-born politician who rose to power as Chancellor and then Führer of Germany in the 1930s, leading the Nazi Party. He initiated World War II in Europe and oversaw the Holocaust, in which approximately six million Jews and millions of others were systematically murdered. He died by suicide in Berlin in April 1945 as Allied forces closed in.",
        "known_for": "World War II, the Holocaust, Nazi Party, Mein Kampf",
    },
    "Buddha (Siddhartha Gautama)": {
        "name": "Buddha (Siddhartha Gautama)",
        "profession": "spiritual teacher",
        "bio": "Born a prince in what is now Nepal around 563 BCE, he renounced his privileged life to seek the end of human suffering. After years of meditation he achieved spiritual awakening under the Bodhi tree and spent the rest of his life teaching the path to liberation. His teachings form the foundation of Buddhism, one of the world's major religions.",
        "known_for": "founding of Buddhism, Four Noble Truths, Eightfold Path, achieving enlightenment",
    },
    "Martin Luther King Jr.": {
        "name": "Martin Luther King Jr.",
        "profession": "civil rights leader",
        "bio": "An American Baptist minister and activist who became the most prominent leader of the U.S. civil rights movement, advocating for nonviolent resistance inspired by Gandhi. He delivered the iconic 'I Have a Dream' speech at the 1963 March on Washington. He was assassinated in Memphis, Tennessee in 1968 at the age of 39.",
        "known_for": "'I Have a Dream' speech, March on Washington, Nobel Peace Prize, Montgomery Bus Boycott",
    },
    "Napoleon Bonaparte": {
        "name": "Napoleon Bonaparte",
        "profession": "emperor",
        "bio": "A French military genius who rose to prominence during the French Revolution and conquered much of Europe as Emperor of the French from 1804 to 1814. He implemented sweeping legal reforms known as the Napoleonic Code that influenced legal systems across the world. He was ultimately defeated at the Battle of Waterloo and died in exile on the remote island of Saint Helena.",
        "known_for": "Battle of Waterloo, Napoleonic Code, conquering Europe, exile to Saint Helena",
    },
    "Leonardo da Vinci": {
        "name": "Leonardo da Vinci",
        "profession": "Renaissance polymath",
        "bio": "An Italian painter, scientist, and inventor of the 15th and 16th centuries, widely regarded as one of the greatest painters of all time and perhaps the most diversely talented person who ever lived. His notebooks contain discoveries in anatomy, astronomy, and engineering that were centuries ahead of their time. He is the archetype of the Renaissance man.",
        "known_for": "Mona Lisa, The Last Supper, Vitruvian Man, scientific notebooks",
    },
    "Isaac Newton": {
        "name": "Isaac Newton",
        "profession": "physicist",
        "bio": "An English mathematician and physicist born in 1643, widely regarded as one of the most influential scientists of all time. He formulated the laws of motion and universal gravitation, laying the foundations for classical mechanics, and independently developed calculus. His landmark work Principia Mathematica transformed our understanding of the physical world.",
        "known_for": "laws of motion, law of universal gravitation, development of calculus, Principia Mathematica",
    },
    "Julius Caesar": {
        "name": "Julius Caesar",
        "profession": "Roman general",
        "bio": "A Roman general and statesman who played a critical role in the transformation of the Roman Republic into the Roman Empire. His conquest of Gaul extended Roman territory to the English Channel, and he was the first Roman general to cross both the Rhine and the English Channel. He was assassinated by a group of senators on the Ides of March, 44 BCE.",
        "known_for": "conquest of Gaul, crossing the Rubicon, assassination on the Ides of March, Gallic Wars",
    },
    "Winston Churchill": {
        "name": "Winston Churchill",
        "profession": "prime minister",
        "bio": "A British statesman who served as Prime Minister of the United Kingdom during World War II, rallying the nation against Nazi Germany with powerful speeches and resolute leadership. He was also a Nobel Prize-winning author and a gifted amateur painter. His wartime oratory, including 'We shall fight on the beaches,' remains iconic to this day.",
        "known_for": "WWII leadership, 'We shall fight on the beaches' speech, Nobel Prize in Literature, Iron Curtain speech",
    },
    "Queen Elizabeth II": {
        "name": "Queen Elizabeth II",
        "profession": "British monarch",
        "bio": "The longest-reigning British monarch in history, she ascended to the throne in 1952 following the death of her father and reigned for 70 years until her death in September 2022. She served as head of state for the United Kingdom and the Commonwealth realms through enormous social and political change. During her reign she met with 13 of the 14 U.S. presidents who served alongside her.",
        "known_for": "longest British reign, Commonwealth leadership, Platinum Jubilee, 70-year reign",
    },
    "Charles Darwin": {
        "name": "Charles Darwin",
        "profession": "naturalist",
        "bio": "An English naturalist and geologist who developed the theory of evolution by natural selection after years of research, including a pivotal voyage aboard HMS Beagle. He published his findings in On the Origin of Species in 1859, fundamentally changing how humans understand the natural world. His ideas remain the foundation of modern evolutionary biology.",
        "known_for": "theory of evolution, On the Origin of Species, voyage of the Beagle, natural selection",
    },
    "Mahatma Gandhi": {
        "name": "Mahatma Gandhi",
        "profession": "independence leader",
        "bio": "An Indian lawyer and activist who became the principal leader of India's independence movement against British colonial rule, championing nonviolent civil disobedience. His philosophy of satyagraha (truth-force) inspired civil rights movements around the world. He was assassinated in January 1948 by a Hindu nationalist, just months after India achieved independence.",
        "known_for": "Indian independence movement, Salt March, nonviolent civil disobedience, assassination in 1948",
    },
    "Alexander the Great": {
        "name": "Alexander the Great",
        "profession": "conqueror",
        "bio": "A king of Macedon who created one of the largest empires in ancient history — stretching from Greece to northwestern India — before the age of 33. Tutored by Aristotle as a boy, he proved to be a brilliant military strategist who never lost a battle. His campaigns spread Greek culture and language across the ancient world in what became the Hellenistic period.",
        "known_for": "conquering Persia and Egypt, founding Alexandria, Battle of Gaugamela, Hellenistic spread of culture",
    },
    "Christopher Columbus": {
        "name": "Christopher Columbus",
        "profession": "explorer",
        "bio": "An Italian explorer sailing under the Spanish crown who completed four voyages across the Atlantic Ocean, opening sustained contact between Europe and the Americas. Though not the first European to reach the New World, his 1492 arrival in the Caribbean is considered a turning point in world history. His voyages initiated the widespread colonization of the Americas.",
        "known_for": "1492 voyage to the Americas, opening the New World, four Atlantic voyages, Columbian Exchange",
    },
    "Mother Teresa": {
        "name": "Mother Teresa",
        "profession": "humanitarian",
        "bio": "An Albanian-Indian Roman Catholic nun who founded the Missionaries of Charity in Calcutta, India in 1950. She devoted her life to caring for the sick, dying, and destitute, establishing hospices and homes across the world. She received the Nobel Peace Prize in 1979 and was canonized as a saint by the Catholic Church in 2016.",
        "known_for": "Missionaries of Charity, Nobel Peace Prize, canonization as saint, work with the poorest of the poor",
    },
    "Plato": {
        "name": "Plato",
        "profession": "ancient philosopher",
        "bio": "An ancient Greek philosopher and student of Socrates who founded the Academy in Athens, one of the earliest institutions of higher learning in the Western world. His philosophical dialogues have been studied for over two millennia and cover topics from justice and beauty to the nature of reality. He is one of the most important figures in the development of Western philosophy.",
        "known_for": "The Republic, Theory of Forms, founding the Academy, philosophical dialogues",
    },
    "Socrates": {
        "name": "Socrates",
        "profession": "ancient philosopher",
        "bio": "An ancient Greek philosopher considered one of the founders of Western philosophy, known for developing the Socratic method of inquiry through questioning. He wrote nothing himself; his ideas survive through the writings of his students, chiefly Plato. He was tried and executed by Athens for allegedly corrupting the youth and impiety, choosing to drink hemlock rather than flee.",
        "known_for": "Socratic method, trial and execution by hemlock, influence on Plato, 'Know thyself'",
    },
    "Karl Marx": {
        "name": "Karl Marx",
        "profession": "political philosopher",
        "bio": "A German philosopher, economist, and revolutionary whose theories about capitalism, class struggle, and historical materialism formed the basis of Marxism and communism. He co-authored The Communist Manifesto with Friedrich Engels in 1848 and spent years producing his landmark work Das Kapital. His ideas profoundly shaped the development of the Soviet Union, China, and other communist states.",
        "known_for": "The Communist Manifesto, Das Kapital, founding of Marxism, critique of capitalism",
    },
    "Benjamin Franklin": {
        "name": "Benjamin Franklin",
        "profession": "founding father",
        "bio": "An American statesman, scientist, and inventor who was one of the Founding Fathers of the United States, helping draft both the Declaration of Independence and the Constitution. His electrical experiments, including the famous kite experiment, led to the invention of the lightning rod. He also founded the first public lending library and the first fire department in America.",
        "known_for": "electricity experiments, Poor Richard's Almanack, Founding Father, bifocals invention",
    },
    "Thomas Jefferson": {
        "name": "Thomas Jefferson",
        "profession": "founding father",
        "bio": "The principal author of the Declaration of Independence and the third President of the United States, serving from 1801 to 1809. He orchestrated the Louisiana Purchase in 1803, effectively doubling the size of the United States. He was also a noted architect, inventor, and founder of the University of Virginia.",
        "known_for": "Declaration of Independence, Louisiana Purchase, third U.S. president, founding University of Virginia",
    },
    "John F. Kennedy": {
        "name": "John F. Kennedy",
        "profession": "U.S. president",
        "bio": "The 35th President of the United States and the youngest person ever elected to the office. He navigated the Cuban Missile Crisis in 1962, bringing the world back from the brink of nuclear war. He was assassinated in Dallas, Texas on November 22, 1963, in one of the most shocking events in American history.",
        "known_for": "Cuban Missile Crisis, assassination in Dallas, moon-shot speech, 'Ask not what your country can do for you'",
    },
    "Nelson Mandela": {
        "name": "Nelson Mandela",
        "profession": "anti-apartheid leader",
        "bio": "A South African anti-apartheid activist who spent 27 years in prison for his opposition to the apartheid regime. After his release he negotiated the end of apartheid and became South Africa's first democratically elected president, serving from 1994 to 1999. He received the Nobel Peace Prize in 1993 and became a global symbol of justice and reconciliation.",
        "known_for": "ending apartheid, 27 years in prison, first South African democratic president, Nobel Peace Prize",
    },
    "Franklin D. Roosevelt": {
        "name": "Franklin D. Roosevelt",
        "profession": "U.S. president",
        "bio": "The 32nd President of the United States, serving a record four terms from 1933 to 1945 through the Great Depression and World War II. He implemented the New Deal, a sweeping series of programs providing relief, recovery, and reform after the economic crisis. The only U.S. president to serve more than two terms, he died in office in April 1945 just weeks before Germany's surrender.",
        "known_for": "New Deal, four presidential terms, leading the U.S. through WWII, overcoming polio",
    },
    "Galileo Galilei": {
        "name": "Galileo Galilei",
        "profession": "astronomer",
        "bio": "An Italian astronomer, physicist, and engineer often called the father of modern science for his pioneering use of the telescope to observe the heavens. His support for the heliocentric model of the solar system brought him into conflict with the Catholic Church, which forced him to recant under threat of torture. He spent the remainder of his life under house arrest.",
        "known_for": "telescope observations, supporting heliocentrism, conflict with the Catholic Church, laws of falling bodies",
    },
    "Sigmund Freud": {
        "name": "Sigmund Freud",
        "profession": "psychoanalyst",
        "bio": "An Austrian neurologist and founder of psychoanalysis, a clinical method for treating psychopathology through dialogue between patient and analyst. He developed influential theories about the unconscious mind, dream interpretation, and the Oedipus complex. Though many of his specific ideas have been superseded, he profoundly shaped 20th-century culture, literature, and thought.",
        "known_for": "founding psychoanalysis, The Interpretation of Dreams, Oedipus complex, theory of the unconscious",
    },
    "Elvis Presley": {
        "name": "Elvis Presley",
        "profession": "rock singer",
        "bio": "Known as the King of Rock and Roll, he is one of the most culturally influential musicians of the 20th century, blending country, rhythm and blues, and gospel into a revolutionary new sound. His energetic performances and good looks made him a global icon in the 1950s. He died at his Graceland estate in Memphis in 1977 at age 42.",
        "known_for": "'Hound Dog', 'Jailhouse Rock', Graceland, Las Vegas residency",
    },
    "Marilyn Monroe": {
        "name": "Marilyn Monroe",
        "profession": "actress",
        "bio": "An American actress, model, and singer who became one of the most recognizable pop culture icons of the 20th century. She rose from a difficult childhood in foster care to become one of Hollywood's biggest stars, excelling in comedic roles. She died of a barbiturate overdose in 1962 at age 36, and her image continues to define an era of Hollywood glamour.",
        "known_for": "'Some Like It Hot', 'Gentlemen Prefer Blondes', JFK birthday serenade, iconic white dress photo",
    },
    "Pablo Picasso": {
        "name": "Pablo Picasso",
        "profession": "artist",
        "bio": "A Spanish painter, sculptor, and printmaker who co-founded the Cubist movement and is widely regarded as one of the most influential artists of the 20th century. Over his long career he created approximately 20,000 works including paintings, sculptures, ceramics, and prints. His anti-war masterpiece Guernica is considered one of the most powerful political statements in modern art.",
        "known_for": "Guernica, Cubism, Les Demoiselles d'Avignon, prolific and diverse output",
    },
    "Ludwig van Beethoven": {
        "name": "Ludwig van Beethoven",
        "profession": "composer",
        "bio": "A German composer and pianist who bridged the Classical and Romantic eras of Western music. Despite becoming completely deaf in his later years, he continued to compose some of his most celebrated works, including his Ninth Symphony. His nine symphonies, five piano concertos, and string quartets remain among the most performed pieces in the classical repertoire.",
        "known_for": "Ninth Symphony ('Ode to Joy'), Moonlight Sonata, composing while deaf, Fifth Symphony",
    },
    "Mozart": {
        "name": "Mozart",
        "profession": "composer",
        "bio": "An Austrian prodigy who began composing at age five and produced over 800 works during his short 35-year life. Widely regarded as one of the greatest composers in the history of Western music, he achieved an unmatched range across virtually every genre of his era. He died in poverty in Vienna in 1791 and was buried in an unmarked grave.",
        "known_for": "The Magic Flute, Don Giovanni, Symphony No. 40, Requiem Mass in D minor",
    },
    "Genghis Khan": {
        "name": "Genghis Khan",
        "profession": "conqueror",
        "bio": "Born Temüjin around 1162, he united the Mongol tribes and founded the Mongol Empire, the largest contiguous land empire in history. His military campaigns were characterized by ruthless efficiency and resulted in the deaths of tens of millions of people. By his death in 1227 he had conquered much of Central Asia, China, and Persia.",
        "known_for": "Mongol Empire, conquering Central Asia and China, Mongolian unification, Pax Mongolica",
    },
    "Joseph Stalin": {
        "name": "Joseph Stalin",
        "profession": "Soviet dictator",
        "bio": "A Georgian revolutionary who became leader of the Soviet Union after Lenin's death, ruling from the mid-1920s until his death in 1953. His forced industrialization and collectivization policies led to the deaths of millions through famine and forced labor. He led the Soviet Union through World War II but maintained a totalitarian police state marked by mass purges and the gulag system.",
        "known_for": "Soviet industrialization, Great Purge, WWII leadership, gulag system",
    },
    "Vladimir Lenin": {
        "name": "Vladimir Lenin",
        "profession": "revolutionary",
        "bio": "A Russian revolutionary and political theorist who led the Bolshevik Revolution of October 1917, overthrowing the provisional government and establishing the world's first communist state. As head of the new Soviet government he navigated the brutal Russian Civil War and implemented a radical socialist economic policy. His embalmed body remains on public display in Moscow's Red Square.",
        "known_for": "Bolshevik Revolution, founding the Soviet Union, 'What Is to Be Done?', New Economic Policy",
    },
    "Steve Jobs": {
        "name": "Steve Jobs",
        "profession": "tech entrepreneur",
        "bio": "An American business magnate who co-founded Apple Inc. and transformed the personal computer, animated film, music, and smartphone industries. After being ousted from Apple in 1985 he returned in 1997 and led the company to become one of the most valuable in the world. He died of pancreatic cancer in 2011, leaving a legacy as one of the most innovative figures in technology history.",
        "known_for": "iPhone, Mac computer, Pixar Studios, 'one more thing' product launches",
    },
    "Bill Gates": {
        "name": "Bill Gates",
        "profession": "tech billionaire",
        "bio": "An American business magnate and philanthropist who co-founded Microsoft and helped transform the personal computer industry by developing software for IBM-compatible PCs. He was the world's wealthiest person for much of the 1990s and 2000s. Through the Bill & Melinda Gates Foundation he has committed tens of billions of dollars to fighting disease and poverty worldwide.",
        "known_for": "founding Microsoft, Windows operating system, Bill & Melinda Gates Foundation, philanthropic work",
    },
    "Michael Jackson": {
        "name": "Michael Jackson",
        "profession": "pop singer",
        "bio": "Known as the King of Pop, he became one of the most commercially successful entertainers in history, transforming the music video into an art form with groundbreaking clips like 'Thriller.' His career began as a child with the Jackson 5 and reached its apex with Thriller, which remains the best-selling album of all time. He died of acute propofol intoxication in 2009 at age 50.",
        "known_for": "Thriller album, moonwalk, 'Billie Jean', child sexual abuse allegations",
    },
    "Taylor Swift": {
        "name": "Taylor Swift",
        "profession": "pop singer",
        "bio": "An American singer-songwriter who began as a country teen sensation and grew into one of the best-selling music artists of all time. Known for writing autobiographical songs about her personal life, she holds the record for the most Grammy Awards won by any artist. Her Eras Tour became the highest-grossing concert tour in history.",
        "known_for": "'Shake It Off', 'Love Story', Eras Tour, re-recording her albums (Taylor's Version)",
    },
    "Oprah Winfrey": {
        "name": "Oprah Winfrey",
        "profession": "TV host",
        "bio": "An American television host, actress, and media mogul who ran the highest-rated daytime talk show in American history for 25 seasons. She overcame a deeply difficult childhood in poverty to become one of the wealthiest and most influential women in the world. Her book club recommendations became a cultural phenomenon, turning selected titles into instant bestsellers.",
        "known_for": "The Oprah Winfrey Show, Oprah's Book Club, 'You get a car!' giveaway, OWN Network",
    },
    "Barack Obama": {
        "name": "Barack Obama",
        "profession": "U.S. president",
        "bio": "The 44th President of the United States and the first African American to hold that office, serving from 2009 to 2017. He signed the Affordable Care Act into law, ended the U.S. combat mission in Iraq, and ordered the operation that resulted in the death of Osama bin Laden. He was awarded the Nobel Peace Prize in 2009, just nine months into his first term.",
        "known_for": "first Black U.S. president, Affordable Care Act, Nobel Peace Prize, killing of Osama bin Laden",
    },
    "Donald Trump": {
        "name": "Donald Trump",
        "profession": "U.S. president",
        "bio": "An American real estate mogul and television personality who served as the 45th and 47th President of the United States. As president he pursued aggressive trade policies, large tax cuts, and a hardline stance on immigration. He was impeached twice by the House of Representatives and became the first U.S. president to be convicted of felony crimes.",
        "known_for": "'Make America Great Again', two impeachments, felony conviction, 'The Apprentice' TV show",
    },
    "Muhammad Ali": {
        "name": "Muhammad Ali",
        "profession": "boxer",
        "bio": "An American professional boxer widely regarded as the greatest heavyweight of all time, known for his exceptional speed, power, and psychological tactics in the ring. He was stripped of his heavyweight title in 1967 for refusing induction into the U.S. military on religious grounds, a stance that defined him as a symbol of conscience. He later reclaimed the title with legendary bouts nicknamed the 'Rumble in the Jungle' and the 'Thrilla in Manila.'",
        "known_for": "'Rumble in the Jungle', 'Thrilla in Manila', conscientious objector to Vietnam, 'Float like a butterfly, sting like a bee'",
    },
    "Michael Jordan": {
        "name": "Michael Jordan",
        "profession": "basketball player",
        "bio": "An American former professional basketball player who played primarily for the Chicago Bulls and is widely considered the greatest basketball player of all time. He led the Bulls to six NBA championships in the 1990s, winning the Finals MVP award each time. His global celebrity and Air Jordan brand permanently transformed the business of sports marketing.",
        "known_for": "six NBA championships, Air Jordan sneakers, 'Space Jam', 'The Last Dance' documentary",
    },
    "LeBron James": {
        "name": "LeBron James",
        "profession": "basketball player",
        "bio": "An American professional basketball player frequently cited alongside Michael Jordan as the greatest of all time. He has won four NBA championships with three different franchises and holds the NBA all-time scoring record. He is one of the first active athletes to own a stake in a major professional sports franchise and is widely recognized for his social justice advocacy.",
        "known_for": "four NBA championships, NBA all-time scoring record, 'The Decision', social activism",
    },
    "Beyoncé": {
        "name": "Beyoncé",
        "profession": "pop singer",
        "bio": "An American singer, songwriter, and actress who rose to fame as the lead vocalist of Destiny's Child before launching one of the most successful solo careers in music history. She holds the record for the most Grammy Awards won by any artist and is considered one of the defining entertainers of her generation. Her visual album Lemonade and her Renaissance album are regarded as landmark works in contemporary music.",
        "known_for": "Lemonade album, Destiny's Child, Grammy record holder, Coachella 2018 performance",
    },
    "Madonna": {
        "name": "Madonna",
        "profession": "pop singer",
        "bio": "An American singer, songwriter, and actress who dominated pop culture in the 1980s and is often called the Queen of Pop. She has continuously reinvented her image and pushed the boundaries of artistic expression in music and video across five decades. With estimated sales of over 300 million records worldwide, she is one of the best-selling music artists in history.",
        "known_for": "'Like a Virgin', 'Material Girl', Blonde Ambition Tour, constantly reinventing her image",
    },
}
