"""
brands.py — master brand list for BrandGuesser.

Each key is the canonical answer players must type.
  search_term : override the default "{name} logo" DDG search
  aliases     : alternate accepted answers (used by the cog, not this script)
"""

BRANDS = {

    # ── Fast Food & Coffee ────────────────────────────────────────────────────
    "McDonald's": {},
    "Burger King": {},
    "Wendy's": {},
    "KFC": {"search_term": "KFC Colonel Sanders logo"},
    "Taco Bell": {},
    "Pizza Hut": {},
    "Domino's": {},
    "Chick-fil-A": {},
    "Dunkin'": {"search_term": "Dunkin Donuts DD logo"},
    "Starbucks": {},
    "Chipotle": {},
    "Jack in the Box": {},
    "Arby's": {},
    "Dairy Queen": {},
    "Popeyes": {},
    "Sonic": {"search_term": "Sonic Drive-In logo"},
    "Whataburger": {},
    "Hardee's": {},
    "Carl's Jr.": {},
    "White Castle": {},
    "Raising Cane's": {"search_term": "Raising Canes chicken logo"},
    "Panda Express": {},
    "Baskin-Robbins": {},
    "Krispy Kreme": {},
    "In-N-Out Burger": {"search_term": "In-N-Out Burger arrow cross logo"},
    "Wingstop": {},
    "Shake Shack": {},
    "Checkers": {"search_term": "Checkers Rally's fast food logo"},
    "Waffle House": {},
    "Tim Hortons": {},

    # ── Sit-Down & Casual Dining ─────────────────────────────────────────────
    "Chili's": {"search_term": "Chilis pepper logo"},
    "Applebee's": {"search_term": "Applebees apple logo"},
    "IHOP": {},
    "Denny's": {},
    "Cracker Barrel": {"search_term": "Cracker Barrel rocking chair logo"},
    "Red Lobster": {"search_term": "Red Lobster lobster logo"},
    "Outback Steakhouse": {"search_term": "Outback Steakhouse kangaroo logo"},
    "Texas Roadhouse": {"search_term": "Texas Roadhouse horse logo"},
    "LongHorn Steakhouse": {"search_term": "LongHorn Steakhouse longhorn skull logo"},
    "Buffalo Wild Wings": {"search_term": "Buffalo Wild Wings wing logo"},
    "Hooters": {"search_term": "Hooters owl logo"},
    "P.F. Chang's": {"search_term": "PF Changs horse statue logo"},
    "Olive Garden": {},
    "Bob Evans": {"search_term": "Bob Evans barn restaurant logo"},

    # ── Tech Companies ───────────────────────────────────────────────────────
    "Apple": {"search_term": "Apple Inc bitten apple logo"},
    "Google": {"search_term": "Google colorful G logo"},
    "Microsoft": {"search_term": "Microsoft four squares logo"},
    "Amazon": {"search_term": "Amazon smile arrow logo"},
    "Meta": {"search_term": "Meta Platforms infinity logo"},
    "Samsung": {"search_term": "Samsung blue oval logo"},
    "Intel": {"search_term": "Intel oval logo"},
    "Dell": {"search_term": "Dell tilted E logo"},
    "HP": {"search_term": "HP Hewlett Packard circle logo"},
    "LG": {"search_term": "LG face smile logo"},
    "NVIDIA": {"search_term": "NVIDIA green eye logo"},
    "AT&T": {"search_term": "AT&T globe sphere logo"},
    "Verizon": {"search_term": "Verizon red checkmark logo"},
    "T-Mobile": {"search_term": "T-Mobile magenta T logo"},
    "Xfinity": {"search_term": "Xfinity Comcast X logo"},
    "GE": {"search_term": "GE General Electric circle logo"},
    "3M": {"search_term": "3M red logo brand"},

    # ── Apps & Social Media ──────────────────────────────────────────────────
    "Instagram": {"search_term": "Instagram camera gradient logo"},
    "Snapchat": {"search_term": "Snapchat ghost logo"},
    "TikTok": {"search_term": "TikTok musical note logo"},
    "YouTube": {"search_term": "YouTube red play button logo"},
    "Netflix": {"search_term": "Netflix red N logo"},
    "Spotify": {"search_term": "Spotify green sound waves logo"},
    "Discord": {"search_term": "Discord purple Wumpus logo"},
    "Reddit": {"search_term": "Reddit orange alien Snoo logo"},
    "Twitter": {"search_term": "Twitter bird logo", "aliases": ["X"]},
    "Pinterest": {"search_term": "Pinterest red P logo"},
    "LinkedIn": {"search_term": "LinkedIn blue in square logo"},
    "WhatsApp": {"search_term": "WhatsApp green phone bubble logo"},
    "Zoom": {"search_term": "Zoom video camera logo"},
    "Airbnb": {"search_term": "Airbnb belo symbol logo"},
    "Uber": {"search_term": "Uber black U logo"},
    "Lyft": {"search_term": "Lyft pink L logo"},
    "PayPal": {"search_term": "PayPal blue PP logo"},
    "Venmo": {"search_term": "Venmo blue V logo"},
    "Duolingo": {"search_term": "Duolingo green owl logo"},
    "Tinder": {"search_term": "Tinder flame logo"},
    "DoorDash": {"search_term": "DoorDash red D logo"},
    "Instacart": {"search_term": "Instacart orange carrot logo"},
    "Shazam": {"search_term": "Shazam blue S logo"},

    # ── Gaming & Streaming ───────────────────────────────────────────────────
    "Xbox": {"search_term": "Xbox green X sphere logo"},
    "PlayStation": {"search_term": "PlayStation PS shapes logo"},
    "Nintendo": {"search_term": "Nintendo red oval logo"},
    "Steam": {"search_term": "Steam gaming logo"},
    "Twitch": {"search_term": "Twitch purple logo"},
    "Roblox": {"search_term": "Roblox red R logo"},
    "Hulu": {"search_term": "Hulu green logo"},
    "Disney+": {"search_term": "Disney Plus logo", "aliases": ["Disney Plus"]},
    "Paramount+": {"search_term": "Paramount mountain stars logo", "aliases": ["Paramount Plus"]},
    "HBO": {"search_term": "HBO logo"},

    # ── Automotive ───────────────────────────────────────────────────────────
    "Toyota": {"search_term": "Toyota three ovals logo"},
    "Honda": {"search_term": "Honda H logo"},
    "Ford": {"search_term": "Ford blue oval logo"},
    "Chevrolet": {"search_term": "Chevrolet bowtie logo", "aliases": ["Chevy"]},
    "BMW": {"search_term": "BMW roundel logo"},
    "Mercedes-Benz": {"search_term": "Mercedes-Benz three pointed star logo", "aliases": ["Mercedes"]},
    "Audi": {"search_term": "Audi four rings logo"},
    "Volkswagen": {"search_term": "Volkswagen VW circle logo", "aliases": ["VW"]},
    "Tesla": {"search_term": "Tesla T logo"},
    "Hyundai": {"search_term": "Hyundai H logo"},
    "Subaru": {"search_term": "Subaru Pleiades stars logo"},
    "Lexus": {"search_term": "Lexus L logo"},
    "Porsche": {"search_term": "Porsche horse crest logo"},
    "Ferrari": {"search_term": "Ferrari prancing horse logo"},
    "Lamborghini": {"search_term": "Lamborghini charging bull logo"},
    "Dodge": {"search_term": "Dodge ram head logo"},
    "Ram": {"search_term": "Ram trucks logo"},
    "Mazda": {"search_term": "Mazda M wing logo"},
    "Mitsubishi": {"search_term": "Mitsubishi three diamond logo"},
    "Infiniti": {"search_term": "Infiniti road logo"},
    "Buick": {"search_term": "Buick tri-shield logo"},
    "Cadillac": {"search_term": "Cadillac crest logo"},
    "Harley-Davidson": {"search_term": "Harley Davidson bar shield eagle logo", "aliases": ["Harley"]},
    "Acura": {"search_term": "Acura A logo"},

    # ── Retail & Stores ──────────────────────────────────────────────────────
    "Target": {"search_term": "Target red bullseye logo"},
    "Walmart": {"search_term": "Walmart yellow spark logo"},
    "Best Buy": {"search_term": "Best Buy yellow tag logo"},
    "Home Depot": {"search_term": "Home Depot orange logo"},
    "Lowe's": {},
    "IKEA": {"search_term": "IKEA blue yellow logo"},
    "Macy's": {"search_term": "Macy's red star logo"},
    "Nordstrom": {},
    "Dollar Tree": {"search_term": "Dollar Tree green tree logo"},
    "Dollar General": {},
    "Walgreens": {},
    "CVS": {"search_term": "CVS heart logo"},
    "GameStop": {},
    "Trader Joe's": {"search_term": "Trader Joes parrot logo"},
    "Whole Foods": {},
    "Costco": {},
    "Kroger": {},
    "TJ Maxx": {},

    # ── Clothing & Footwear ──────────────────────────────────────────────────
    "Nike": {"search_term": "Nike swoosh logo"},
    "Adidas": {"search_term": "Adidas three stripes trefoil logo"},
    "Puma": {"search_term": "Puma leaping cat logo"},
    "Under Armour": {"search_term": "Under Armour UA logo"},
    "New Balance": {"search_term": "New Balance N logo"},
    "Reebok": {"search_term": "Reebok delta vector logo"},
    "Converse": {"search_term": "Converse star chevron logo"},
    "Vans": {"search_term": "Vans wavy V logo"},
    "Ralph Lauren": {"search_term": "Ralph Lauren polo player horse logo", "aliases": ["Polo Ralph Lauren"]},
    "Lacoste": {"search_term": "Lacoste crocodile logo"},
    "Tommy Hilfiger": {"search_term": "Tommy Hilfiger flag logo"},
    "North Face": {"search_term": "North Face half dome logo"},
    "Patagonia": {"search_term": "Patagonia mountain logo"},
    "Columbia": {"search_term": "Columbia Sportswear logo"},
    "Levi's": {"search_term": "Levis batwing logo", "aliases": ["Levis"]},
    "Champion": {"search_term": "Champion C script logo"},
    "Carhartt": {"search_term": "Carhartt C logo"},
    "Versace": {"search_term": "Versace Medusa head logo"},
    "Coach": {"search_term": "Coach horse carriage leather logo"},

    # ── Gas Stations & Convenience ───────────────────────────────────────────
    "Shell": {"search_term": "Shell scallop logo"},
    "BP": {"search_term": "BP sunflower green yellow logo"},
    "Chevron": {"search_term": "Chevron gas station V logo"},
    "QuikTrip": {"search_term": "QuikTrip QT logo", "aliases": ["QT"]},
    "Circle K": {},
    "7-Eleven": {},
    "Wawa": {"search_term": "Wawa goose logo"},
    "Mobil": {"search_term": "Mobil Pegasus flying horse logo"},
    "Marathon": {"search_term": "Marathon gas station logo"},
    "Speedway": {"search_term": "Speedway gas station flag logo"},

    # ── Insurance & Financial ─────────────────────────────────────────────────
    "State Farm": {"search_term": "State Farm three ovals logo"},
    "GEICO": {"search_term": "GEICO gecko logo"},
    "Allstate": {"search_term": "Allstate good hands logo"},
    "Mastercard": {"search_term": "Mastercard two circles logo"},
    "American Express": {"search_term": "American Express centurion logo", "aliases": ["Amex"]},
    "Chase": {"search_term": "Chase bank octagon logo"},
    "Bank of America": {"search_term": "Bank of America flag logo"},
    "Nationwide": {"search_term": "Nationwide eagle logo"},
    "Liberty Mutual": {"search_term": "Liberty Mutual Statue of Liberty logo"},
    "Visa": {"search_term": "Visa credit card logo"},
    "Wells Fargo": {"search_term": "Wells Fargo stagecoach logo"},
    "Citibank": {"search_term": "Citibank arc logo", "aliases": ["Citi"]},
    "Capital One": {"search_term": "Capital One bank logo"},
    "Progressive": {"search_term": "Progressive insurance logo"},

    # ── Airlines ─────────────────────────────────────────────────────────────
    "Southwest Airlines": {"search_term": "Southwest Airlines heart logo", "aliases": ["Southwest"]},
    "Delta": {"search_term": "Delta Airlines triangle logo"},
    "American Airlines": {"search_term": "American Airlines eagle logo", "aliases": ["American"]},
    "Alaska Airlines": {"search_term": "Alaska Airlines Eskimo face logo", "aliases": ["Alaska"]},
    "United Airlines": {"search_term": "United Airlines globe logo", "aliases": ["United"]},
    "Spirit Airlines": {"search_term": "Spirit Airlines sun logo", "aliases": ["Spirit"]},
    "Frontier Airlines": {"search_term": "Frontier Airlines animal tail logo", "aliases": ["Frontier"]},

    # ── Sports Leagues & Broadcast ───────────────────────────────────────────
    "NFL": {"search_term": "NFL shield football logo"},
    "NBA": {"search_term": "NBA player silhouette logo"},
    "MLB": {"search_term": "MLB batter silhouette logo"},
    "NHL": {"search_term": "NHL shield logo"},
    "ESPN": {"search_term": "ESPN logo"},
    "NBC": {"search_term": "NBC peacock logo"},
    "CBS": {"search_term": "CBS eye logo"},
    "ABC": {"search_term": "ABC network circle logo"},
    "Disney": {"search_term": "Disney D logo Mickey"},
    "Warner Bros.": {"search_term": "Warner Bros WB shield logo", "aliases": ["Warner Brothers"]},
    "Universal": {"search_term": "Universal Studios globe logo"},
    "Paramount": {"search_term": "Paramount Pictures mountain logo"},
    "DreamWorks": {"search_term": "DreamWorks boy moon logo"},
    "Pixar": {"search_term": "Pixar Luxo lamp logo"},
    "Fox": {"search_term": "Fox Broadcasting Network logo"},
    "NASA": {"search_term": "NASA meatball logo"},
    "Hallmark": {"search_term": "Hallmark crown logo"},

    # ── Shipping & Delivery ──────────────────────────────────────────────────
    "FedEx": {"search_term": "FedEx purple orange logo"},
    "UPS": {"search_term": "UPS brown shield logo"},
    "USPS": {"search_term": "USPS eagle logo"},
    "DHL": {"search_term": "DHL yellow red logo"},

    # ── Beverages & Food Products ─────────────────────────────────────────────
    "Coca-Cola": {"search_term": "Coca-Cola script logo", "aliases": ["Coke"]},
    "Pepsi": {"search_term": "Pepsi globe logo"},
    "Red Bull": {"search_term": "Red Bull two bulls logo"},
    "Monster Energy": {"search_term": "Monster Energy claw logo", "aliases": ["Monster"]},
    "Gatorade": {"search_term": "Gatorade lightning bolt G logo"},
    "Planters": {"search_term": "Planters Mr Peanut logo"},
    "Heineken": {"search_term": "Heineken red star green logo"},
    "Tide": {"search_term": "Tide laundry detergent orange swirl logo"},
    "Dove": {"search_term": "Dove soap bird logo"},
    "Mr. Clean": {"search_term": "Mr Clean bald man logo"},
    "Pringles": {"search_term": "Pringles Mr P face mustache logo"},
    "Cheetos": {"search_term": "Cheetos Chester Cheetah logo"},
    "M&M's": {"search_term": "M&Ms candy character logo", "aliases": ["M&Ms"]},
    "Oreo": {"search_term": "Oreo cookie logo"},

    # ── Alcohol & Spirits ────────────────────────────────────────────────────
    "Bacardi": {"search_term": "Bacardi bat rum logo"},
    "Captain Morgan": {"search_term": "Captain Morgan rum logo"},
    "Corona": {"search_term": "Corona beer crown logo"},
    "Modelo": {"search_term": "Modelo eagle beer logo"},
    "Blue Moon": {"search_term": "Blue Moon beer moon logo"},
    "Guinness": {"search_term": "Guinness harp beer logo"},
    "Patron": {"search_term": "Patron tequila bee logo"},
    "Johnnie Walker": {"search_term": "Johnnie Walker striding man logo"},
    "Crown Royal": {"search_term": "Crown Royal crown bag logo"},
    "Grey Goose": {"search_term": "Grey Goose vodka goose logo"},
    "Jose Cuervo": {"search_term": "Jose Cuervo crow logo"},
    "Budweiser": {"search_term": "Budweiser Anheuser-Busch eagle bowtie logo"},

    # ── Household & Personal Care ─────────────────────────────────────────────
    "Charmin": {"search_term": "Charmin bear logo"},
    "Old Spice": {"search_term": "Old Spice ship logo"},
    "Gillette": {"search_term": "Gillette razor G logo"},
    "Colgate": {"search_term": "Colgate toothpaste logo"},
    "Febreze": {"search_term": "Febreze swirl logo"},

    # ── Hotels & Travel ──────────────────────────────────────────────────────
    "Marriott": {"search_term": "Marriott hotel M logo"},
    "Hilton": {"search_term": "Hilton Hotels H logo"},
    "Hyatt": {"search_term": "Hyatt Hotels logo"},
    "Ritz-Carlton": {"search_term": "Ritz Carlton lion crown logo"},
    "Best Western": {"search_term": "Best Western crown logo"},
    "Expedia": {"search_term": "Expedia travel logo"},
    "TripAdvisor": {"search_term": "TripAdvisor owl logo"},

    # ── Miscellaneous ─────────────────────────────────────────────────────────
    "Red Cross": {"search_term": "American Red Cross logo"},
    "LEGO": {"search_term": "LEGO brick logo"},
    "Hot Wheels": {"search_term": "Hot Wheels flame logo"},
    "Barbie": {"search_term": "Barbie pink logo"},
    "Rolex": {"search_term": "Rolex crown logo"},
    "Omega": {"search_term": "Omega watch Greek letter logo"},
    "Kate Spade": {"search_term": "Kate Spade spade logo"},
    "Tiffany & Co.": {"search_term": "Tiffany blue box logo", "aliases": ["Tiffany"]},
    "AAA": {"search_term": "AAA roadside assistance logo"},
}
